### ISSUE TITLE
Using Defender correctly

### ISSUE THREAD

**Issue by ngw** [sarahhodne-abandoned/defender#5]
Hi, I followed the documentation but without success. Sorry if the body of some comments contain some vulgarity, I'm testing :)

```
User.last.messages.each do |m|
    puts m.spam?
    puts m.body
    puts m.defensio_data
end; nil

false
Viagra buy viagra
{}
false
Fuck fuck
{}
```

This is my model: https://gist.github.com/d1ce80aad9ca70f963f0

The empty defensio_data hash makes me think that I'm doing something wrong in my model.

Any clues?

**Comment by sarahhodne** [comment]
It looks like you're not giving Defender your API key. To give it your defensio API key, create an initializer file and call `Defensio.api_key = "YOUR API KEY"` in it, or call `configure_defender :api_key => "YOUR API KEY"` in the model.

Defender does not modify `defensio_data`, it's only for you to pass data that you don't want to store in the model, like the HTTP headers or cookies. So the fact that it's empty is to be expected.

**Comment by ngw** [comment]
Hi, I have it in the initializer. I'm the one who opened the ticket about it actually :)

https://gist.github.com/def0feffd023ef3aa67a

Here is the data. As you can see spamminess is not set. I don't know if it's important, but I'm on mongoid.

**Comment by sarahhodne** [comment]
Oh, doi. I thought there was something familiar with your username.

Well, you misspelled `spaminess`, but `spam` should've been set. Defender should be compatible with all ActiveModel-compliant libraries, so the fact that you're using Mongoid shouldn't matter. I'll try to see if I can replicate this.

UPDATE: Turns out I can't try and replicate it right now, I'm at the Newark airport and can't get mongoid installed. Could you please try and use a modified version of defender (clone the repo and build/install) and modify _defender_before_save to print `document` at the end and see if `'allow'` is one of the keys? If I don't hear back from you I'll check it out once I come back to Oslo, but that won't be for another 10 hours or so.

**Comment by ngw** [comment]
Weird, after correcting spaminess I have this data:

```
#<Message _id: 4e02790a367d7880c5000006, _type: nil, spam: false, spamminess: nil, defensio_sig: "be7f1f7320690c4b54f89c", body: "viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra viagra ", author: "ngw", email: "ngw@nofeed.org", url: "http://nofeed.org", user_id: BSON::ObjectId('4de59133367d788ff2000003'), spaminess: 0.05>
```

Seems a problem of defensio honestly ...

**Comment by ngw** [comment]
I meant spaminess set to 0.05%

**Comment by ngw** [comment]
I had an answer from defensio support that redirected me to http://help.defensio.com/entries/20217443-i-cannot-get-defensio-to-give-me-the-result-i-want.
I would say it's definitely not a defender problem, I'm gonna close this one.

**Comment by ngw** [comment]
If someone has the same problem here is how I'm putting defensio in test mode:

```
before_save do
    if Rails.env != 'production'
        self.defensio_data( { 'type' => 'test' } )
    end
end
```

**Comment by sarahhodne** [comment]
Thank you. I'll add a way to set Defender in test mode shortly.
